"""Equipment__unique_constraint

Revision ID: 03a1f74f76e1
Revises: d1b532af91db
Create Date: 2025-05-08 16:42:56.875042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03a1f74f76e1'
down_revision: Union[str, None] = 'd1b532af91db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_serial_per_type', 'Equipment', ['serial_number', 'equipment_type_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_serial_per_type', 'Equipment', type_='unique')
    # ### end Alembic commands ###
