"""initial

Revision ID: 3c0901c4eff5
Revises: 
Create Date: 2025-05-07 17:20:56.300598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c0901c4eff5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EquipmentType',
    sa.Column('name', sa.String(1000), nullable=False),
    sa.Column('serial_number_mask', sa.String(100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Equipment',
    sa.Column('note', sa.String(1000), nullable=False),
    sa.Column('equipment_type_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_type_id'], ['EquipmentType.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Equipment')
    op.drop_table('EquipmentType')
    # ### end Alembic commands ###
