"""Equipment__is_deleted

Revision ID: d1b532af91db
Revises: 3c0901c4eff5
Create Date: 2025-05-08 15:00:54.678656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1b532af91db'
down_revision: Union[str, None] = '3c0901c4eff5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Equipment', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Equipment', 'is_deleted')
    # ### end Alembic commands ###
