"""identity

Revision ID: ed2c39b6387f
Revises: 03a1f74f76e1
Create Date: 2025-05-15 16:42:55.728375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed2c39b6387f'
down_revision: Union[str, None] = '03a1f74f76e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Roles',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Users',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('middle_name', sa.String(length=256), nullable=False),
    sa.Column('surname', sa.String(length=256), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RefreshSessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('expires_in', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=256), nullable=False),
    sa.Column('user_agent', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserRoles',
    sa.Column('UserId', sa.Uuid(), nullable=True),
    sa.Column('RoleId', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['RoleId'], ['Roles.id'], ),
    sa.ForeignKeyConstraint(['UserId'], ['Users.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserRoles')
    op.drop_table('RefreshSessions')
    op.drop_table('Users')
    op.drop_table('Roles')
    # ### end Alembic commands ###
